spring:
  datasource:
    url: jdbc:h2:men:sdw2023
    username: sdw2023
    password: 
    jpa:
    show-sql: tue
    open-in-view: false
    hibernate:
    addl-auto: create # validade | update | create | create-drop
    properties:
    hibernate:
    format-sql: true
    h2:
    console:
    enabled: true
    path: /h2-console
    settings:
    trace: false
    we-allow-others: false
    
    
    
        